meta_product_name: "To Be Found"
meta_title: "To Be Found - Help the indegenous people save the Amazon rainforest."
meta_description: "To Be Found connects people who want to help with organisations who need help in the Amazon rainforest area."
meta_image: "meta-image.jpg" # should exist in `app/assets/images/`
