meta_product_name: "To Be Found"
meta_title: "To Be Found - Donations Webpage"
meta_description: "To Be Found is a Weppage that focuses on helping the indegenous people save the Amazon rainforest"
meta_image: "meta-image.jpg" # should exist in `app/assets/images/`
